// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

export interface ChangePasswordReq {
	oldPassword: string // 旧密码
	newPassword: string // 新密码
	code: string // 验证码
}

export interface ChangePasswordResp {
}

export interface LoginReq {
	email: string // 邮箱
	password: string // 密码
	rememberMe?: boolean // 记住我，默认 false
}

export interface LoginResp {
	accessToken: string // 短期令牌，单位:秒
	refreshToken?: string // 长期令牌，单位:秒
	expiresIn: number // AccessToken 有效期，单位:秒
}

export interface RefreshTokenReq {
	refreshToken: string // 刷新令牌
}

export interface RefreshTokenResp {
	accessToken: string // 短期令牌，单位:秒
	refreshToken: string // 长期令牌，单位:秒
	expiresIn: number // AccessToken 有效期，单位:秒
}

export interface RegisterReq {
	email: string // 邮箱
	password: string // 密码
	code: string // 验证码
	nickname: string // 昵称
}

export interface RegisterResp {
}

export interface ResetPasswordReq {
	email: string // 邮箱
	password: string // 新密码
	code: string // 验证码
}

export interface ResetPasswordResp {
}

export interface SendVerifyCodeReq {
	email: string // 邮箱地址
	type: string // 验证码类型: register/reset_password/bind_email
}

export interface SendVerifyCodeResp {
	retryAfter: number // 多少秒后可重发
}

export interface VerificationCodeMessage {
	code: string // 验证码
	receiver: string // 接收方邮箱
	type: string // 验证码类型（注册/登录/重置密码）
	timestamp: number // 时间戳，用于过期判断
}

